"""empty message

Revision ID: 0d07d5db3de8
Revises: 
Create Date: 2023-06-21 11:41:11.523693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d07d5db3de8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sa.String(length=255), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accessory_trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], name=op.f('fk_accessory_trainings_accessory_id_accessories')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compound_trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('compound_lift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compound_lift_id'], ['compounds.id'], name=op.f('fk_compound_trainings_compound_lift_id_compounds')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('max_lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('squat_max', sa.Integer(), nullable=False),
    sa.Column('bench_max', sa.Integer(), nullable=False),
    sa.Column('deadlift_max', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_max_lifts_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_programs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('training_program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], name=op.f('fk_workout_sessions_training_program_id_training_programs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sessions')
    op.drop_table('training_programs')
    op.drop_table('max_lifts')
    op.drop_table('compound_trainings')
    op.drop_table('accessory_trainings')
    op.drop_table('users')
    op.drop_table('compounds')
    op.drop_table('accessories')
    # ### end Alembic commands ###
