"""empty message

Revision ID: d4c8c919026f
Revises: b0d03aed19e5
Create Date: 2023-06-21 15:27:32.609976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c8c919026f'
down_revision = 'b0d03aed19e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessory_trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_program_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_accessory_trainings_training_program_id_training_programs'), 'training_programs', ['training_program_id'], ['id'])

    with op.batch_alter_table('compound_trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_program_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_compound_trainings_training_program_id_training_programs'), 'training_programs', ['training_program_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compound_trainings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_compound_trainings_training_program_id_training_programs'), type_='foreignkey')
        batch_op.drop_column('training_program_id')

    with op.batch_alter_table('accessory_trainings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_accessory_trainings_training_program_id_training_programs'), type_='foreignkey')
        batch_op.drop_column('training_program_id')

    # ### end Alembic commands ###
